export type PayrollComplianceType =
  | 'NONE'
  | 'FEDERAL_DAVIS_BACON'
  | 'MISSOURI_LS57'
  | 'BOTH'
  | 'OTHER';

export type CertifiedPayrollProjectStatus =
  | 'Not Started'
  | 'Setup'
  | 'In Progress'
  | 'Current'
  | 'Final Needed'
  | 'Complete';

export type CertifiedPayrollWeekStatus =
  | 'setup'
  | 'draft'
  | 'blocked'
  | 'ready'
  | 'submitted'
  | 'exported';

export type CertifiedPayrollTaskStatus =
  | 'Not Started'
  | 'In Progress'
  | 'Waiting'
  | 'Complete'
  | 'Canceled';

export type CertifiedPayrollExceptionType =
  | 'missing-employee-info'
  | 'missing-classification'
  | 'unknown-classification'
  | 'missing-wage-rate'
  | 'missing-fringe-rate'
  | 'unapproved-time'
  | 'adp-time-mismatch'
  | 'missing-wage-order'
  | 'missing-county'
  | 'missing-public-body'
  | 'final-payroll-needed'
  | 'unmapped-labor-code'
  | 'labor-code-missing-classification';

export type CertifiedPayrollTaskKey =
  | 'setup-needed'
  | 'confirm-wage-order'
  | 'confirm-classifications'
  | 'confirm-rates'
  | 'review-time-logs'
  | 'generate-draft'
  | 'resolve-exceptions'
  | 'submit-package'
  | 'upload-backup'
  | 'final-payroll-needed';

export interface CertifiedPayrollWeek {
  id: string;
  projectId: string;
  weekEnding: string;
  status: CertifiedPayrollWeekStatus;
  regularHours: number;
  overtimeHours: number;
  doubleTimeHours: number;
  totalHours: number;
  entryCount: number;
  exceptionCount: number;
  readyAt?: string;
  submittedAt?: string;
  exportedAt?: string;
  notes?: string;
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface CertifiedPayrollDailyHours {
  workDate: string;
  regularHours: number;
  overtimeHours: number;
  doubleTimeHours: number;
}

export interface CertifiedPayrollEntry {
  id: string;
  weekId: string;
  projectId: string;
  weekEnding: string;
  employeeName: string;
  classification: string;
  laborCode?: string;
  dailyHours: CertifiedPayrollDailyHours[];
  regularHours: number;
  overtimeHours: number;
  doubleTimeHours: number;
  totalHours: number;
  baseRate?: number;
  fringeRate?: number;
  totalPackage?: number;
  regularWage: number;
  overtimeWage: number;
  doubleTimeWage: number;
  fringeAmount: number;
  grossPackage: number;
  employeePayrollInfoId?: string;
  adpPayrollDetailId?: string;
  sourceEntryIds?: string[];
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface CertifiedPayrollException {
  id: string;
  projectId: string;
  weekId?: string;
  entryId?: string;
  type: CertifiedPayrollExceptionType;
  severity: 'warning' | 'error';
  message: string;
  employeeName?: string;
  workDate?: string;
  classification?: string;
  resolved: boolean;
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface CertifiedPayrollTask {
  id: string;
  projectId: string;
  taskKey: CertifiedPayrollTaskKey;
  title: string;
  description?: string;
  status: CertifiedPayrollTaskStatus;
  priority?: 'Low' | 'Medium' | 'High' | 'Critical';
  sortOrder: number;
  autoGenerated: boolean;
  category: 'certified-payroll';
  relatedWeekId?: string;
  assignedTo?: string;
  dueDate?: string;
  completedAt?: string;
  notes?: string;
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface CertifiedPayrollExport {
  id: string;
  projectId: string;
  weekId: string;
  weekEnding: string;
  destination: 'google-sheet' | 'manual';
  sheetId?: string;
  rowCount: number;
  status: 'pending' | 'success' | 'failed';
  message?: string;
  exportedAt?: string;
  ownerId?: string;
  createdAt?: unknown;
}

export interface StoredClassificationRate {
  id: string;
  unionArea: string;
  classification: string;
  baseRate: number;
  fringeRate: number;
  totalPackage: number;
  effectiveDate?: string;
  source?: string;
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface StoredFringeRate {
  id: string;
  unionArea: string;
  classification: string;
  fringeRate: number;
  effectiveDate?: string;
  source?: string;
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface EmployeePayrollInfo {
  id: string;
  employeeKey: string;
  employeeName: string;
  legalName?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  ssnLast4?: string;
  defaultClassification?: string;
  unionId?: string;
  apprenticePeriod?: string;
  fringeEligible?: boolean;
  notes?: string;
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface AdpPayrollDetail {
  id: string;
  employeeKey: string;
  employeeName: string;
  payPeriodEnding?: string;
  regularHours?: number;
  overtimeHours?: number;
  doubleTimeHours?: number;
  grossPay?: number;
  regularRate?: number;
  overtimeRate?: number;
  socialSecurity?: number;
  medicare?: number;
  federalIncomeTax?: number;
  stateTaxKs?: number;
  stateTaxMo?: number;
  unionDues?: number;
  vacationDeduction?: number;
  netPay?: number;
  source?: string;
  ownerId?: string;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface CertifiedPayrollDashboardKpis {
  certifiedProjects: number;
  openTasks: number;
  draftWeeks: number;
  blockedWeeks: number;
  readyWeeks: number;
  openExceptions: number;
  exportConfigured: boolean;
}

export const CERTIFIED_PAYROLL_TASK_TEMPLATES: Array<{
  taskKey: CertifiedPayrollTaskKey;
  title: string;
  description: string;
  sortOrder: number;
  priority: 'Low' | 'Medium' | 'High' | 'Critical';
}> = [
  { taskKey: 'setup-needed', title: 'Certified payroll setup needed', description: 'Complete prevailing wage / certified payroll project fields.', sortOrder: 1, priority: 'High' },
  { taskKey: 'confirm-wage-order', title: 'Confirm wage order / AWO', description: 'Verify wage determination or agency wage order number.', sortOrder: 2, priority: 'High' },
  { taskKey: 'confirm-classifications', title: 'Confirm project classifications', description: 'Confirm classifications used on this job match the wage order.', sortOrder: 3, priority: 'Medium' },
  { taskKey: 'confirm-rates', title: 'Confirm employee wage/fringe rates', description: 'Verify base and fringe rates for each employee/classification.', sortOrder: 4, priority: 'High' },
  { taskKey: 'review-time-logs', title: 'Review approved time logs', description: 'Review approved timekeeper rows for this project.', sortOrder: 5, priority: 'Medium' },
  { taskKey: 'generate-draft', title: 'Generate certified payroll draft', description: 'Build weekly certified payroll draft from approved time.', sortOrder: 6, priority: 'High' },
  { taskKey: 'resolve-exceptions', title: 'Resolve certified payroll exceptions', description: 'Clear missing rate, classification, or ADP mismatch exceptions.', sortOrder: 7, priority: 'Critical' },
  { taskKey: 'submit-package', title: 'Submit certified payroll package', description: 'Submit WH-347 / LS-57 package to agency or prime.', sortOrder: 8, priority: 'High' },
  { taskKey: 'upload-backup', title: 'Upload signed CPR / eStamp backup', description: 'Store signed certified payroll or eStamp confirmation.', sortOrder: 9, priority: 'Medium' },
  { taskKey: 'final-payroll-needed', title: 'Final certified payroll needed', description: 'Project closeout requires final certified payroll submission.', sortOrder: 10, priority: 'High' },
];
