import { ForemanBonusPolicy, ForemanBonusRecord } from '@app/models/foreman-bonus.types';

export const DEFAULT_FOREMAN_BONUS_POLICY: ForemanBonusPolicy = {
  id: 'policy-brighten-default',
  name: 'Brighten Foreman Labor Savings Bonus',
  defaultBonusRate: 0.10,
  laborCostBasis: 'WagesPlusFringe',
  releaseBasis: 'BilledPercent',
  defaultPayoutTiming: 'Quarterly',
  allowSplits: true,
  allowNegativePayThisTerm: false,
  active: true,
};

export const dustinJob163: ForemanBonusRecord = {
  id: 'seed-dustin-163',
  projectId: 'seed-job-163',
  jobNumber: '163',
  projectName: 'LPS Heritage',
  foremanName: 'Dustin Miller',
  reportPeriodEnd: '2025-11-30',
  laborCostBasis: 'WagesPlusFringe',
  actualLaborCost: 207602.39,
  laborBudget: 263791.20,
  percentComplete: 0.93,
  currentLaborBudget: 245325.82,
  laborSavings: 37723.43,
  bonusRate: 0.15,
  grossBonusEarned: 5658.51,
  foremanSharePercent: 1,
  foremanShareBonus: 5658.51,
  billingReleasePercent: 0.5162,
  bonusAvailableToReceive: 2920.92,
  previouslyPaid: 0,
  payThisTerm: 2920.92,
  remainingPotential: 2737.59,
  status: 'Calculated',
  source: 'ImportedHistorical',
  notes: '15% bonus rate',
};

export const kyleJob155: ForemanBonusRecord = {
  id: 'seed-kyle-155',
  projectId: 'seed-job-155',
  jobNumber: '155',
  projectName: 'Park Hill',
  foremanName: 'Kyle Patterson',
  reportPeriodEnd: '2025-11-30',
  laborCostBasis: 'WagesPlusFringe',
  actualLaborCost: 57448.22,
  laborBudget: 77700,
  percentComplete: 1,
  currentLaborBudget: 77700,
  laborSavings: 20251.78,
  bonusRate: 0.10,
  grossBonusEarned: 2025.18,
  foremanSharePercent: 1,
  foremanShareBonus: 2025.18,
  billingReleasePercent: 0.8796,
  bonusAvailableToReceive: 1781.35,
  previouslyPaid: 1863.58,
  payThisTerm: -82.20,
  remainingPotential: 161.60,
  status: 'NeedsReview',
  source: 'ImportedHistorical',
  notes: 'Historical record has negative pay-this-term. Preserve imported value and flag NeedsReview unless allowNegativePayThisTerm is enabled.',
};
