import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/dashboard').then(m => m.Dashboard) },
  { path: 'active-2026-control', loadComponent: () => import('./pages/active-2026-control-page').then(m => m.Active2026ControlPage) },
  { path: 'projects', loadComponent: () => import('./pages/projects').then(m => m.Projects) },
  { path: 'projects/:id', loadComponent: () => import('./pages/project-details').then(m => m.ProjectDetails) },
  { path: 'financials', loadComponent: () => import('./pages/financials-hub-page').then(m => m.FinancialsHubPage) },
  { path: 'directory', loadComponent: () => import('./pages/directory-hub-page').then(m => m.DirectoryHubPage) },
  { path: 'billing', loadComponent: () => import('./pages/billing').then(m => m.Billing) },
  { path: 'wip', loadComponent: () => import('./pages/wip-page').then(m => m.WipPage) },
  { path: 'ar', loadComponent: () => import('./pages/ar-page').then(m => m.ArPage) },
  { path: 'pos', loadComponent: () => import('./pages/pos-page').then(m => m.PosPage) },
  { path: 'changes', loadComponent: () => import('./pages/changes').then(m => m.Changes) },
  { path: 'tasks', loadComponent: () => import('./pages/tasks-hub-page').then(m => m.TasksHubPage) },
  { path: 'tasks/board', loadComponent: () => import('./pages/tasks').then(m => m.Tasks) },
  { path: 'rfis', loadComponent: () => import('./pages/rfis').then(m => m.Rfis) },
  { path: 'submittals', loadComponent: () => import('./pages/submittals-page').then(m => m.Submittals) },
  { path: 'daily-logs', loadComponent: () => import('./pages/daily-logs').then(m => m.DailyLogs) },
  { path: 'field-issues', loadComponent: () => import('./pages/field-issues-page').then(m => m.FieldIssuesPage) },
  { path: 'documents', loadComponent: () => import('./pages/documents-page').then(m => m.Documents) },
  { path: 'subcontractors', loadComponent: () => import('./pages/subcontractors-page').then(m => m.SubcontractorsPage) },
  { path: 'certified-payroll', loadComponent: () => import('./pages/certified-payroll').then(m => m.CertifiedPayroll) },
  { path: 'labor-actuals', loadComponent: () => import('./pages/labor-actuals-page').then(m => m.LaborActualsPage) },
  { path: 'foreman-bonuses', loadComponent: () => import('./pages/foreman-bonuses-page').then(m => m.ForemanBonusesPage) },
  { path: 'labor', loadComponent: () => import('./pages/labor').then(m => m.Labor) },
  { path: 'reports', loadComponent: () => import('./pages/reports').then(m => m.Reports) },
  { path: 'settings', loadComponent: () => import('./pages/settings').then(m => m.Settings) },
  { path: '**', redirectTo: '' }
];
