import { Injectable, inject } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import {
  CERTIFIED_PAYROLL_TASK_TEMPLATES,
  CertifiedPayrollTask,
} from '@app/models/certified-payroll.types';
import { Project } from '@app/models/types';
import { CertifiedPayrollDataService } from '@features/labor/services/certified-payroll-data.service';
import { isCertifiedPayrollProject } from '@features/labor/utils/certified-payroll-week';

@Injectable({ providedIn: 'root' })
export class CertifiedPayrollTasksService {
  private cprData = inject(CertifiedPayrollDataService);

  async ensureTasksForProject(project: Project): Promise<number> {
    if (!isCertifiedPayrollProject(project)) return 0;

    const existing = this.cprData.getTasksSnapshot().filter(t => t.projectId === project.id);
    let created = 0;

    for (const template of CERTIFIED_PAYROLL_TASK_TEMPLATES) {
      const hasTask = existing.some(t => t.taskKey === template.taskKey);
      if (hasTask) continue;

      await firstValueFrom(this.cprData.createTask({
        projectId: project.id,
        taskKey: template.taskKey,
        title: template.title,
        description: template.description,
        sortOrder: template.sortOrder,
        priority: template.priority,
        status: 'Not Started',
        autoGenerated: true,
        category: 'certified-payroll',
      }));
      created += 1;
    }

    if (!project.certifiedPayrollStatus || project.certifiedPayrollStatus === 'Not Started') {
      // Status bump handled by caller if needed.
    }

    return created;
  }

  async ensureTasksForProjects(projects: Project[]): Promise<number> {
    let total = 0;
    for (const project of projects.filter(isCertifiedPayrollProject)) {
      total += await this.ensureTasksForProject(project);
    }
    return total;
  }

  syncTaskProgress(project: Project, openExceptionCount: number, readyWeekCount: number): void {
    const tasks = this.cprData.getTasksSnapshot().filter(t => t.projectId === project.id);
    const weeks = this.cprData.getWeeksSnapshot().filter(w => w.projectId === project.id);
    const submittedWeekCount = weeks.filter(w => w.status === 'submitted' || w.status === 'exported').length;

    const updateIf = (taskKey: CertifiedPayrollTask['taskKey'], complete: boolean) => {
      const task = tasks.find(t => t.taskKey === taskKey);
      if (!task) return;
      if (complete && task.status !== 'Complete') {
        void firstValueFrom(this.cprData.updateTask(task.id, {
          status: 'Complete',
          completedAt: new Date().toISOString(),
        }));
      }
    };

    updateIf('setup-needed', !!(project.wageOrderNumber && project.county && project.publicBody));
    updateIf('confirm-wage-order', !!project.wageOrderNumber);
    updateIf('confirm-classifications', !!project.payrollComplianceType && project.payrollComplianceType !== 'NONE');
    updateIf('review-time-logs', readyWeekCount > 0 || openExceptionCount === 0);
    updateIf('generate-draft', readyWeekCount > 0 || submittedWeekCount > 0);
    updateIf('resolve-exceptions', openExceptionCount === 0 && readyWeekCount > 0);
    updateIf('submit-package', submittedWeekCount > 0);
    updateIf('upload-backup', weeks.some(w => w.status === 'exported'));
    updateIf('final-payroll-needed', project.certifiedPayrollStatus === 'Complete');
  }

  async ensureWeeklyGenerateTask(project: Project): Promise<void> {
    if (!isCertifiedPayrollProject(project)) return;

    await this.ensureTasksForProject(project);

    const tasks = this.cprData.getTasksSnapshot().filter(t => t.projectId === project.id);
    const generateTask = tasks.find(t => t.taskKey === 'generate-draft');
    const template = CERTIFIED_PAYROLL_TASK_TEMPLATES.find(t => t.taskKey === 'generate-draft');

    if (generateTask?.status === 'Complete') {
      await firstValueFrom(this.cprData.updateTask(generateTask.id, {
        status: 'Not Started',
        completedAt: undefined,
      }));
    } else if (!generateTask && template) {
      await firstValueFrom(this.cprData.createTask({
        projectId: project.id,
        taskKey: template.taskKey,
        title: template.title,
        description: template.description,
        sortOrder: template.sortOrder,
        priority: template.priority,
        status: 'Not Started',
        autoGenerated: true,
        category: 'certified-payroll',
      }));
    }

    await this.ensureFinalPayrollTask(project);
  }

  async ensureFinalPayrollTask(project: Project): Promise<void> {
    if (!isCertifiedPayrollProject(project)) return;
    if (project.status !== 'Closeout' && project.status !== 'Closed') return;
    if (project.certifiedPayrollStatus === 'Complete') return;

    const tasks = this.cprData.getTasksSnapshot().filter(t => t.projectId === project.id);
    const finalTask = tasks.find(t => t.taskKey === 'final-payroll-needed');
    const template = CERTIFIED_PAYROLL_TASK_TEMPLATES.find(t => t.taskKey === 'final-payroll-needed');

    if (finalTask && finalTask.status === 'Complete') {
      await firstValueFrom(this.cprData.updateTask(finalTask.id, { status: 'Not Started', completedAt: undefined }));
    } else if (!finalTask && template) {
      await firstValueFrom(this.cprData.createTask({
        projectId: project.id,
        taskKey: template.taskKey,
        title: template.title,
        description: template.description,
        sortOrder: template.sortOrder,
        priority: template.priority,
        status: 'Not Started',
        autoGenerated: true,
        category: 'certified-payroll',
      }));
    }
  }

  async completeWeeklyTasksForSubmittedWeek(projectId: string, weekId: string): Promise<void> {
    const tasks = this.cprData.getTasksSnapshot().filter(t =>
      t.projectId === projectId
      && (t.taskKey === 'generate-draft' || t.taskKey === 'submit-package' || t.taskKey === 'resolve-exceptions')
      && t.status !== 'Complete',
    );

    for (const task of tasks) {
      await firstValueFrom(this.cprData.updateTask(task.id, {
        status: 'Complete',
        completedAt: new Date().toISOString(),
        relatedWeekId: weekId,
      }));
    }
  }
}
